### ISSUE TITLE
Optimization of code: read PDB files only once if multiple entries use the same PDB file

### ISSUE THREAD

**Issue by alexandrefassio** [keiserlab/LUNA#23]
Usually, in Docking projects, one sets N entries, where each ligand points out to a different MOL file, but to the same PDB file (all molecules were docked against the same structure, right!?). So, it'd be better if LUNA creates a cache system for PDB structures to make the PDB parsing happen only once.

The same cache system could be applied for Interactions involving residue-residue interactions. It would be much better if we save these interactions instead of recalculating the same things over and over again.

**Comment by alexandrefassio** [comment]
@laurashub, LUNA now provides full integration between command lines and LUNA config files. I think this will be especially useful for your project.

**Comment by laurashub** [comment]
> @laurashub, LUNA now provides full integration between command lines and LUNA config files. I think this will be especially useful for your project.

Awesome, thank you so much! That will be super helpful for https://github.com/keiserlab/keiserlab-pfizer/issues/17
