### ISSUE TITLE
No module named 'Bio.__py3k' error

### ISSUE THREAD

**Issue by satvikkg** [keiserlab/LUNA#36]
Hello,
        Unable to install luna. I tried installing via pip and also from source. Every time I get an error that says No module named 'Bio.__py3k'. I tried installing biopython from both pip and conda. It would be greate if you could help me figure out how to get luna installed. Looking forward to hear from you.

**Comment by alexandrefassio** [comment]
Hi @satvikkg,

Thanks for your interest in using LUNA. Soon I'll add support to install LUNA entirely through CONDA. But, meanwhile, try the following:

1. Download the LUNA repo.
2. Create a LUNA environment:
    
     - open the file **luna-env.yml**, and add the following line at the beginning of the file:
            `name: luna-env`

     - then, run:
            `$ conda env create -f luna-env.yml`
     
3. After creating the conda environment, activate it:
            `$ conda activate luna-env`

4. Finally, install LUNA:
            `$ pip install luna`

Please, try these steps and let me know if you have any further issues.

bests

**Comment by laurashub** [comment]
Adding a bit more detail to this, that error comes from Biopython version issue: LUNA specifically uses biopython=1.72, while py3k was discontinued from 1.76 onward. Hopefully fixing that through installing directly into the luna-env.yml conda environment as @alexandrefassio described should get rid of any import issues.

**Comment by satvikkg** [comment]
Hi @alexandrefassio,
  Installing the dependencies from the luna-env.yml file and then installing luna from pip worked like a charm. Thank you.

**Comment by abazabaaa** [comment]
Biopython 1.72 does not work with apple silicon based osx (there does not appear to be any way to install it via pip or condo), making luna unusable on these machines.

**Comment by abazabaaa** [comment]
Nevermind! I was able to build everything by installing biopython via pip..

https://pypi.org/project/biopython/1.72/
