### ISSUE TITLE
No module named 'Bio._py3k'

### ISSUE THREAD

**Issue by pducrot** [keiserlab/LUNA#37]
Hi,
Installation of luna fails on MacBook Pro running macOS Monterey 12.4 (21F79) with the following message, although biopython was installed with pip previously.
No module named 'Bio._py3k' 
I used pip to install luna:
pip install -U luna 
Thanks
Pierre

**Comment by abazabaaa** [comment]
See here: https://github.com/keiserlab/LUNA/issues/36

If you are on apple silicon you can install biopython via pip and it will still work.

**Comment by pducrot** [comment]
Thanks for the quick answer, I’m still on intel unfortunately.

**Comment by abazabaaa** [comment]
You should be able to just use the luna_env.yml file in this repo to install. There are instructions in issue 36 for solving this exact problem.

https://github.com/keiserlab/LUNA/issues/36#issuecomment-1255526293

**Comment by alexandrefassio** [comment]
Hi @pducrot, 

Have you tried following the instructions in issue #36 as suggested by @abazabaaa ?

The explicit requirement of the Biopython 1.72 version will be solved soon. I also plan to add full compatibility with Conda. Then all dependencies will be solved with a single command.

Meanwhile, you can try to follow the mentioned steps, which should work. Let me know if it doesn't.

bests

**Comment by pducrot** [comment]
Hi @alexandrefassio, I had not but just did and it worked, thanks. I see that several packages have older version than in my usual env, Biopython was indeed one of these.
Best
