### ISSUE TITLE
Tutorial #3 little bug

### ISSUE THREAD

**Issue by pducrot** [keiserlab/LUNA#40]
Hi, I noticed a little bug in the cell #9 of tutorial #3 in which opt should be replaced by opts as below.
```
if not os.path.exists("%s/project_v%s.pkl.gz" % (opts["working_path"], __version__)):
    proj_obj = luna.projects.LocalProject(**opts)
    proj_obj.run()
else:
    print("Reloading project...")
    print()
    proj_obj = LocalProject.load(opts["working_path"], verbosity=3, logging_enabled=True)
```

**Comment by alexandrefassio** [comment]
Thanks, @pducrot, for letting me know about this bug and your interest in LUNA.

I'm gonna update the LUNA repo with the fixes you pointed out. Thanks.
