### ISSUE TITLE
No module named 'luna.config'

### ISSUE THREAD

**Issue by pducrot** [keiserlab/LUNA#41]
Hi,
I get a 'ModuleNotFoundError' when running the most basic command line Intel-based MacBook Pro / MacOS X 12.4

Traceback (most recent call last):
  File "luna/run.py", line 13, in <module>
    from luna.config.params import ProjectParams
ModuleNotFoundError: No module named 'luna.config'

Thanks

**Comment by alexandrefassio** [comment]
Hi @pducrot, sorry about this.

Have you installed LUNA through PIP? Maybe you need to update your LUNA version. Could you check out if the version installed on your PC is 0.12.1? If it's not, it should work as soon as you update the LUNA package.

bests

**Comment by pducrot** [comment]
Actuelly, i installés using instructions from issue #36. I was missing proper setup of PYTHONPATH in the luna-env environnement. All fine, thanks.
